from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(330, 200)
        Dialog.setWindowTitle("Runique Exp Calculator")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Pictures/Photoshop/Runique/Logo..png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        Dialog.setAutoFillBackground(False)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.currentGamemode = QtWidgets.QComboBox(Dialog)
        self.currentGamemode.setGeometry(QtCore.QRect(50, 40, 111, 22))
        self.currentGamemode.setObjectName("currentGamemode")
        self.currentGamemode.addItem("")
        self.currentGamemode.addItem("")
        self.currentGamemode.addItem("")
        self.currentGamemode.addItem("")
        self.currentGamemode.addItem("")
        self.currentGamemode.addItem("")
        self.newGamemode = QtWidgets.QComboBox(Dialog)
        self.newGamemode.setGeometry(QtCore.QRect(200, 40, 111, 22))
        self.newGamemode.setObjectName("newGamemode")
        self.newGamemode.addItem("")
        self.newGamemode.addItem("")
        self.newGamemode.addItem("")
        self.newGamemode.addItem("")
        self.newGamemode.addItem("")
        self.newGamemode.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 10, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.calculateButton = QtWidgets.QPushButton(Dialog)
        self.calculateButton.setGeometry(QtCore.QRect(200, 160, 111, 21))
        self.calculateButton.setObjectName("calculateButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(170, 40, 20, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(6, 70, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.currentXp = QtWidgets.QSpinBox(Dialog)
        self.currentXp.setGeometry(QtCore.QRect(50, 70, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.currentXp.setFont(font)
        self.currentXp.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.currentXp.setAlignment(QtCore.Qt.AlignCenter)
        self.currentXp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.currentXp.setProperty("showGroupSeparator", True)
        self.currentXp.setMaximum(200000000)
        self.currentXp.setSingleStep(1000)
        self.currentXp.setObjectName("currentXp")
        self.currentLevel = QtWidgets.QSpinBox(Dialog)
        self.currentLevel.setGeometry(QtCore.QRect(50, 100, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.currentLevel.setFont(font)
        self.currentLevel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.currentLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentLevel.setReadOnly(True)
        self.currentLevel.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.currentLevel.setProperty("showGroupSeparator", True)
        self.currentLevel.setMaximum(200000000)
        self.currentLevel.setSingleStep(1000)
        self.currentLevel.setObjectName("currentLevel")
        self.calculatedLevel = QtWidgets.QSpinBox(Dialog)
        self.calculatedLevel.setGeometry(QtCore.QRect(200, 100, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.calculatedLevel.setFont(font)
        self.calculatedLevel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.calculatedLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.calculatedLevel.setReadOnly(True)
        self.calculatedLevel.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.calculatedLevel.setProperty("showGroupSeparator", True)
        self.calculatedLevel.setMaximum(200000000)
        self.calculatedLevel.setSingleStep(1000)
        self.calculatedLevel.setObjectName("calculatedLevel")
        self.calculatedXp = QtWidgets.QSpinBox(Dialog)
        self.calculatedXp.setGeometry(QtCore.QRect(200, 70, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.calculatedXp.setFont(font)
        self.calculatedXp.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.calculatedXp.setAlignment(QtCore.Qt.AlignCenter)
        self.calculatedXp.setReadOnly(True)
        self.calculatedXp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.calculatedXp.setProperty("showGroupSeparator", True)
        self.calculatedXp.setMaximum(200000000)
        self.calculatedXp.setSingleStep(1000)
        self.calculatedXp.setObjectName("calculatedXp")
        self.enteredLvlCompared = QtWidgets.QSpinBox(Dialog)
        self.enteredLvlCompared.setGeometry(QtCore.QRect(120, 130, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.enteredLvlCompared.setFont(font)
        self.enteredLvlCompared.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.enteredLvlCompared.setAlignment(QtCore.Qt.AlignCenter)
        self.enteredLvlCompared.setReadOnly(False)
        self.enteredLvlCompared.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.enteredLvlCompared.setProperty("showGroupSeparator", True)
        self.enteredLvlCompared.setMaximum(99)
        self.enteredLvlCompared.setSingleStep(1)
        self.enteredLvlCompared.setProperty("value", 99)
        self.enteredLvlCompared.setObjectName("enteredLvlCompared")
        self.calculatedXpTill99 = QtWidgets.QSpinBox(Dialog)
        self.calculatedXpTill99.setGeometry(QtCore.QRect(50, 160, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.calculatedXpTill99.setFont(font)
        self.calculatedXpTill99.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.calculatedXpTill99.setAlignment(QtCore.Qt.AlignCenter)
        self.calculatedXpTill99.setReadOnly(True)
        self.calculatedXpTill99.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.calculatedXpTill99.setProperty("showGroupSeparator", True)
        self.calculatedXpTill99.setMaximum(2000000000)
        self.calculatedXpTill99.setSingleStep(1000)
        self.calculatedXpTill99.setObjectName("calculatedXpTill99")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.currentGamemode, self.newGamemode)
        Dialog.setTabOrder(self.newGamemode, self.calculateButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.currentGamemode.setItemText(0, _translate("Dialog", "Extreme"))
        self.currentGamemode.setItemText(1, _translate("Dialog", "Legend"))
        self.currentGamemode.setItemText(2, _translate("Dialog", "Iron Man"))
        self.currentGamemode.setItemText(3, _translate("Dialog", "Immortal"))
        self.currentGamemode.setItemText(4, _translate("Dialog", "Hardcore Iron Man"))
        self.currentGamemode.setItemText(5, _translate("Dialog", "Grand Master"))
        self.newGamemode.setItemText(0, _translate("Dialog", "Extreme"))
        self.newGamemode.setItemText(1, _translate("Dialog", "Legend"))
        self.newGamemode.setItemText(2, _translate("Dialog", "Iron Man"))
        self.newGamemode.setItemText(3, _translate("Dialog", "Immortal"))
        self.newGamemode.setItemText(4, _translate("Dialog", "Hardcore Iron Man"))
        self.newGamemode.setItemText(5, _translate("Dialog", "Grand Master"))
        self.label.setText(_translate("Dialog", "Current"))
        self.label_2.setText(_translate("Dialog", "To"))
        self.calculateButton.setText(_translate("Dialog", "Calculate"))
        self.label_3.setText(_translate("Dialog", "Exp till: "))
        self.label_4.setText(_translate("Dialog", "Exp:"))
        self.label_5.setText(_translate("Dialog", "Lvl: "))
        self.currentXp.setToolTip(_translate("Dialog", "Input the base-xp you\'d like to calculate off."))
        self.currentLevel.setToolTip(_translate("Dialog", "The current level based off the current Exp."))
        self.calculatedLevel.setToolTip(_translate("Dialog", "The calculated level."))
        self.calculatedXp.setToolTip(_translate("Dialog", "The calculated Exp."))
        self.enteredLvlCompared.setToolTip(_translate("Dialog", "Enter the level you wish to achieve in the new gamemode before you convert."))
        self.calculatedXpTill99.setToolTip(_translate("Dialog", "The Exp you\'d need to reach to achieve set level above."))
        self.label_6.setText(_translate("Dialog", "Exp: "))